use-conda: True 
cluster: "sbatch --parsable -p engreitz --ntasks 1 --cpus-per-task {threads} --mem {resources.mem_gb} --time {resources.runtime_hr}:00"
cluster-cancel: scancel
default-resources: "runtime_hr=4"
jobs: 100
rerun-triggers: mtime
